### Get all events
GET http://localhost:8080/events


### Create an event
POST http://localhost:8080/events
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "test3",
  "description": "test3",
  "location": "test3",
  "date_time": "1985-03-02T15:30:00.000Z"
}


### Get event by ID
GET http://localhost:8080/events/1


### Update an event
PUT http://localhost:8080/events/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "test3",
  "description": "test3",
  "location": "test3",
  "date_time": "1985-03-02T15:30:00.000Z"
}


### Delete event by ID
DELETE http://localhost:8080/events/2
Authorization: Bearer {{token}}


### Register an event to logged in user
POST http://localhost:8080/events/11/register
Authorization: Bearer {{token}}